### ISSUE TITLE
chrome.runtime.onMessage.addListener seems not listening on the message we send.

### ISSUE THREAD

**Issue by nggih** [buildspace/gpt3-writer-extension-starter#3]
Hi, I am stuck at Injecting into the Calmly webpage. I have followed the https://buildspace.so/p/build-ai-writing-assistant-gpt3/lessons/inject-into-a-webpage and final repo, but the error below still occur and the result from API can't be injected on the Calmly. Any help would be appreciated. Thank you.

Chrome version: Version 108.0.5359.99 (Official Build) (64-bit)

![image](https://user-images.githubusercontent.com/8409460/206897074-81617e92-2caa-47f2-888f-66136d3e91da.png)
`Unchecked runtime.lastError: Cannot create item with duplicate id context-run
Error handling response: TypeError: Cannot read properties of undefined (reading 'status')
    at chrome-extension://fmhgmgocffondhgalcpcllfaggcllhko/scripts/contextMenuServiceWorker.js:21:22
Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.
Error handling response: TypeError: Cannot read properties of undefined (reading 'id')
    at chrome-extension://fmhgmgocffondhgalcpcllfaggcllhko/scripts/contextMenuServiceWorker.js:15:31`

**Comment by benthecoder** [comment]
faced the same thing, did you find a fix @nggih ?
